// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var Nav$ReactHooksTemplate = require("./Nav.bs.js");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");
var Layout$ReactHooksTemplate = require("./Layout.bs.js");
var Recipes$ReactHooksTemplate = require("./Recipes.bs.js");

var main = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.minHeight(Css.pct(100)),
        /* :: */[
          Css.gridTemplateColumns(/* :: */[
                Css.rem(25),
                /* :: */[
                  Css.fr(3),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Css.margin2(Css.rem(Theme$ReactHooksTemplate.navHeight), /* auto */-1065951377),
            /* [] */0
          ]
        ]
      ]
    ]);

var sidebar = Css.style(/* :: */[
      Css.gridColumnStart(1),
      /* [] */0
    ]);

var content = Css.style(/* :: */[
      Css.marginTop(Css.rem(2.5)),
      /* :: */[
        Css.gridColumnStart(2),
        /* :: */[
          Css.gridColumnEnd(2),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* main */main,
  /* sidebar */sidebar,
  /* content */content
];

function App(Props) {
  return React.createElement(Layout$ReactHooksTemplate.make, {
              children: null
            }, React.createElement(Nav$ReactHooksTemplate.make, { }), React.createElement("main", {
                  className: main
                }, React.createElement("aside", {
                      className: sidebar
                    }, "Sidebar"), React.createElement("div", {
                      className: content
                    }, React.createElement(Recipes$ReactHooksTemplate.make, { }))));
}

var make = App;

exports.Styles = Styles;
exports.make = make;
/* main Not a pure module */
