// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/lib/js/src/ReasonReactRouter.js");
var Nav$ReactHooksTemplate = require("./Nav.bs.js");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");
var Layout$ReactHooksTemplate = require("./Layout.bs.js");
var Recipes$ReactHooksTemplate = require("./Recipes.bs.js");
var RecipeEdit$ReactHooksTemplate = require("./RecipeEdit.bs.js");

var main = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.minHeight(Css.pct(100)),
        /* :: */[
          Css.gridTemplateColumns(/* :: */[
                Css.rem(25),
                /* :: */[
                  Css.fr(3),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Css.margin2(Css.rem(Theme$ReactHooksTemplate.navHeight), /* auto */-1065951377),
            /* [] */0
          ]
        ]
      ]
    ]);

var sidebar = Css.style(/* :: */[
      Css.gridColumnStart(1),
      /* [] */0
    ]);

var content = Css.style(/* :: */[
      Css.marginTop(Css.rem(2.5)),
      /* :: */[
        Css.gridColumnStart(2),
        /* :: */[
          Css.gridColumnEnd(2),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* main */main,
  /* sidebar */sidebar,
  /* content */content
];

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "recipe" : 
          var match$1 = match[1];
          if (match$1) {
            var match$2 = match$1[1];
            if (match$2 && match$2[0] === "edit" && !match$2[1]) {
              return /* RecipeEditPage */2;
            } else {
              return /* Home */0;
            }
          } else {
            return /* Home */0;
          }
      case "shoppingList" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* ShoppingList */1;
          }
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

function App(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* route */action[0]];
        }), /* record */[/* route */mapUrlToRoute(ReasonReactRouter.useUrl(undefined, /* () */0))]);
  var dispatch = match[1];
  React.useEffect((function () {
          var watcherId = ReasonReactRouter.watchUrl((function (url) {
                  return Curry._1(dispatch, /* UpdatePage */[mapUrlToRoute(url)]);
                }));
          return (function (param) {
                    return ReasonReactRouter.unwatchUrl(watcherId);
                  });
        }), ([]));
  var match$1 = match[0][/* route */0];
  var tmp;
  switch (match$1) {
    case 0 : 
        tmp = React.createElement(React.Fragment, undefined, React.createElement("aside", {
                  className: sidebar
                }, "Sidebar"), React.createElement("div", {
                  className: content
                }, React.createElement(Recipes$ReactHooksTemplate.make, { })));
        break;
    case 1 : 
        tmp = React.createElement("div", undefined, "ShoppingList");
        break;
    case 2 : 
        tmp = React.createElement(RecipeEdit$ReactHooksTemplate.make, { });
        break;
    
  }
  return React.createElement(Layout$ReactHooksTemplate.make, {
              children: null
            }, React.createElement(Nav$ReactHooksTemplate.make, { }), React.createElement("main", {
                  className: main
                }, tmp));
}

var make = App;

exports.Styles = Styles;
exports.mapUrlToRoute = mapUrlToRoute;
exports.make = make;
/* main Not a pure module */
