// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/lib/js/src/ReasonReactRouter.js");
var Nav$ReactHooksTemplate = require("./Nav.bs.js");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");
var Layout$ReactHooksTemplate = require("./Layout.bs.js");
var Recipes$ReactHooksTemplate = require("./Recipes.bs.js");

var main = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.minHeight(Css.pct(100)),
        /* :: */[
          Css.gridTemplateColumns(/* :: */[
                Css.rem(25),
                /* :: */[
                  Css.fr(3),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Css.margin2(Css.rem(Theme$ReactHooksTemplate.navHeight), /* auto */-1065951377),
            /* [] */0
          ]
        ]
      ]
    ]);

var sidebar = Css.style(/* :: */[
      Css.gridColumnStart(1),
      /* [] */0
    ]);

var content = Css.style(/* :: */[
      Css.marginTop(Css.rem(2.5)),
      /* :: */[
        Css.gridColumnStart(2),
        /* :: */[
          Css.gridColumnEnd(2),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* main */main,
  /* sidebar */sidebar,
  /* content */content
];

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match && match[0] === "shoppingList" && !match[1]) {
    return /* ShoppingList */1;
  } else {
    return /* Home */0;
  }
}

function App(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* route */action[0]];
        }), /* record */[/* route */mapUrlToRoute(ReasonReactRouter.useUrl(undefined, /* () */0))]);
  var dispatch = match[1];
  React.useEffect((function () {
          var watcherId = ReasonReactRouter.watchUrl((function (url) {
                  return Curry._1(dispatch, /* UpdatePage */[mapUrlToRoute(url)]);
                }));
          return (function (param) {
                    return ReasonReactRouter.unwatchUrl(watcherId);
                  });
        }), ([]));
  var match$1 = match[0][/* route */0];
  return React.createElement(Layout$ReactHooksTemplate.make, {
              children: null
            }, React.createElement(Nav$ReactHooksTemplate.make, { }), React.createElement("main", {
                  className: main
                }, match$1 ? React.createElement("div", undefined, "ShoppingList") : React.createElement(React.Fragment, undefined, React.createElement("aside", {
                            className: sidebar
                          }, "Sidebar"), React.createElement("div", {
                            className: content
                          }, React.createElement(Recipes$ReactHooksTemplate.make, { })))));
}

var make = App;

exports.Styles = Styles;
exports.mapUrlToRoute = mapUrlToRoute;
exports.make = make;
/* main Not a pure module */
