// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/lib/js/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/lib/js/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/lib/js/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

function contextHandler(param) {
  return {
          headers: {
            authorization: "Bearer " + (String("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJ0b2tlbklkIjoiNjI3Y2FkZGUtMjVkYy00MzZhLTlhMmYtZmMzMWY3OWY0YTYxIn0.L-90eKbtVaZG0JBnRWx85BIqJc9_Af3PRtMbTL1Fshg") + "")
          }
        };
}

var authLink = ApolloLinks.createContextLink(contextHandler);

var httpLink = ApolloLinks.createHttpLink("https://api-euwest.graphcms.com/v1/cjvtuzuav5tux01etrbx95u65/master", undefined, undefined, undefined, undefined, undefined, /* () */0);

var instance = ReasonApollo.createApolloClient(ApolloLink.from(/* array */[
          authLink,
          httpLink
        ]), inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

exports.inMemoryCache = inMemoryCache;
exports.contextHandler = contextHandler;
exports.authLink = authLink;
exports.httpLink = httpLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
