// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function makeProps($staropt$star, $staropt$star$1, param) {
  var size = $staropt$star !== undefined ? $staropt$star : 24;
  var color = $staropt$star$1 !== undefined ? $staropt$star$1 : "#333";
  return {
          size: size,
          color: color
        };
}

var Edit = /* module */[/* makeProps */makeProps];

exports.Edit = Edit;
/* No side effect */
