// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");

Css.$$global("html", /* :: */[
      Css.fontSize(Css.px(10)),
      /* [] */0
    ]);

Css.$$global("html, body, #root", /* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* [] */0
      ]
    ]);

Css.$$global("*,\n          *:before,\n          *:after ", /* :: */[
      Css.boxSizing(/* inherit_ */-601204732),
      /* [] */0
    ]);

Css.$$global("body", /* :: */[
      Css.padding(Css.zero),
      /* :: */[
        Css.margin(Css.zero),
        /* :: */[
          Css.fontSize(Css.rem(1.5)),
          /* :: */[
            Css.color(Css.hex(Theme$ReactHooksTemplate.colorText)),
            /* :: */[
              Css.background(Css.hex(Theme$ReactHooksTemplate.colorBg)),
              /* :: */[
                Css.lineHeight(Css.rem(2)),
                /* :: */[
                  Css.fontFamily("-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,\n              Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue',\n              sans-serif"),
                  /* :: */[
                    Css.minHeight(Css.pct(100)),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

Css.$$global("a", /* :: */[
      Css.textDecoration(/* none */-922086728),
      /* [] */0
    ]);

var GlobalStyles = /* module */[];

function Layout(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, children);
}

var make = Layout;

exports.GlobalStyles = GlobalStyles;
exports.make = make;
/*  Not a pure module */
