// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/lib/js/src/ReasonReactRouter.js");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");

var nav = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(/* spaceBetween */516682146),
        /* :: */[
          Css.background(Css.hex(Theme$ReactHooksTemplate.colorCyan)),
          /* :: */[
            Css.color(Css.hex(Theme$ReactHooksTemplate.colorBg)),
            /* :: */[
              Css.position(/* fixed */10615156),
              /* :: */[
                Css.top(Css.rem(0)),
                /* :: */[
                  Css.left(Css.rem(0)),
                  /* :: */[
                    Css.width(Css.pct(100)),
                    /* :: */[
                      Css.height(Css.rem(Theme$ReactHooksTemplate.navHeight)),
                      /* :: */[
                        Css.zIndex(9),
                        /* :: */[
                          /* `transition */[
                            -659583595,
                            "background 250ms ease-in-out 0s,\n        box-shadow 250ms ease-in-out 0s"
                          ],
                          /* :: */[
                            /* `shadow */[
                              488687584,
                              "0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);"
                            ],
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var menu = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* row */5693978),
        /* :: */[
          Css.flexWrap(/* nowrap */867913355),
          /* :: */[
            Css.justifyContent(/* flexEnd */924268066),
            /* :: */[
              Css.alignItems(/* center */98248149),
              /* :: */[
                Css.height(Css.pct(100)),
                /* :: */[
                  Css.alignSelf(/* flexEnd */924268066),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var brand = Css.style(/* :: */[
      Css.marginLeft(Css.rem(1.5)),
      /* :: */[
        Css.display(/* flex */-1010954439),
        /* :: */[
          Css.justifyContent(/* center */98248149),
          /* :: */[
            Css.alignItems(/* center */98248149),
            /* :: */[
              Css.height(Css.pct(100)),
              /* :: */[
                Css.width(Css.rem(15)),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var item = Css.style(/* :: */[
      Css.position(/* relative */903134412),
      /* :: */[
        Css.display(/* flex */-1010954439),
        /* :: */[
          Css.justifyContent(/* center */98248149),
          /* :: */[
            Css.alignItems(/* center */98248149),
            /* :: */[
              Css.boxSizing(/* borderBox */9307263),
              /* :: */[
                Css.height(Css.pct(100)),
                /* :: */[
                  Css.marginRight(Css.rem(1.5)),
                  /* :: */[
                    Css.padding2(/* zero */-789508312, Css.rem(1)),
                    /* :: */[
                      Css.cursor(/* pointer */-786317123),
                      /* :: */[
                        Css.before(/* :: */[
                              Css.unsafe("content", ""),
                              /* :: */[
                                Css.position(/* absolute */-1013592457),
                                /* :: */[
                                  Css.left(Css.pct(50)),
                                  /* :: */[
                                    Css.bottom(Css.pct(20)),
                                    /* :: */[
                                      Css.width(Css.pct(85)),
                                      /* :: */[
                                        Css.height(Css.px(2)),
                                        /* :: */[
                                          Css.backgroundColor(Css.hex(Theme$ReactHooksTemplate.colorBg)),
                                          /* :: */[
                                            Css.unsafe("transform-origin", "center"),
                                            /* :: */[
                                              Css.unsafe("transform", "translate(-50%, 0) scaleX(0)"),
                                              /* :: */[
                                                Css.unsafe("transition", "transform 0.3s ease-in-out"),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]),
                        /* :: */[
                          Css.hover(/* :: */[
                                Css.before(/* :: */[
                                      Css.unsafe("transform", "translate(-50%, 0) scaleX(1)"),
                                      /* [] */0
                                    ]),
                                /* [] */0
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var NavStyles = /* module */[
  /* nav */nav,
  /* menu */menu,
  /* brand */brand,
  /* item */item
];

function Nav(Props) {
  return React.createElement("nav", {
              className: nav
            }, React.createElement("div", {
                  className: brand
                }, React.createElement("h2", undefined, "Recipe Book")), React.createElement("div", {
                  className: menu
                }, React.createElement("a", {
                      className: item,
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/");
                        })
                    }, "Recipes"), React.createElement("a", {
                      className: item,
                      onClick: (function (param) {
                          return ReasonReactRouter.push("/shoppingList");
                        })
                    }, "Shopping-List")));
}

var make = Nav;

exports.NavStyles = NavStyles;
exports.make = make;
/* nav Not a pure module */
