// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");

var card = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.height(Css.rem(30)),
          /* :: */[
            Css.width(Css.rem(30)),
            /* :: */[
              Css.backgroundColor(Css.hex("fff")),
              /* :: */[
                /* `shadow */[
                  488687584,
                  "0 1px 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);"
                ],
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* card */card];

function Recipe(Props) {
  var recipe = Props.recipe;
  return React.createElement("li", {
              className: card
            }, React.createElement("div", undefined, recipe.title), React.createElement("div", undefined, "Card"));
}

var make = Recipe;

exports.Styles = Styles;
exports.make = make;
/* card Not a pure module */
