// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReactFeather = require("react-feather");
var Theme$ReactHooksTemplate = require("./Theme.bs.js");
var FeaterIcons$ReactHooksTemplate = require("./FeaterIcons.bs.js");

var card = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.overflow(/* hidden */-862584982),
        /* :: */[
          Css.flexDirection(/* column */-963948842),
          /* :: */[
            Css.justifyContent(/* spaceBetween */516682146),
            /* :: */[
              Css.height(Css.rem(35)),
              /* :: */[
                Css.width(Css.rem(35)),
                /* :: */[
                  Css.backgroundColor(Css.hex("fff")),
                  /* :: */[
                    /* `shadow */[
                      488687584,
                      "0px 1px 3px 0px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 2px 1px -1px rgba(0,0,0,0.12)"
                    ],
                    /* :: */[
                      Css.borderRadius(Css.px(4)),
                      /* :: */[
                        Css.maxWidth(Css.rem(35)),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var cardImageWrapper = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.position(/* relative */903134412),
          /* :: */[
            Css.height(Css.px(280)),
            /* [] */0
          ]
        ]
      ]
    ]);

var cardImage = Css.style(/* :: */[
      Css.display(/* block */888960333),
      /* :: */[
        Css.width(Css.pct(100)),
        /* :: */[
          Css.height(Css.pct(100)),
          /* :: */[
            Css.backgroundSize(/* cover */-899416265),
            /* :: */[
              Css.backgroundRepeat(/* noRepeat */-695430532),
              /* :: */[
                Css.unsafe("background-position", "center"),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var cardTitle = Css.style(/* :: */[
      Css.display(/* inlineBlock */-147785676),
      /* :: */[
        Css.position(/* absolute */-1013592457),
        /* :: */[
          Css.right(Css.px(-3)),
          /* :: */[
            Css.bottom(Css.px(-3)),
            /* :: */[
              Css.fontSize(Css.rem(3)),
              /* :: */[
                Css.transform(/* `rotate */[
                      -887077285,
                      Css.deg(3)
                    ]),
                /* :: */[
                  Css.fontWeight(/* `num */[
                        5496390,
                        600
                      ]),
                  /* :: */[
                    Css.padding(Css.rem(0.75)),
                    /* :: */[
                      Css.color(Css.hex(Theme$ReactHooksTemplate.colorBg)),
                      /* :: */[
                        Css.backgroundColor(Css.hex(Theme$ReactHooksTemplate.colorPink)),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var cardContent = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.height(Css.rem(8.5)),
          /* :: */[
            Css.padding(Css.rem(1.6)),
            /* [] */0
          ]
        ]
      ]
    ]);

var cardDescription = Css.style(/* :: */[
      Css.margin(/* zero */-789508312),
      /* :: */[
        Css.fontSize(Css.rem(1.4)),
        /* :: */[
          Css.fontWeight(/* `num */[
                5496390,
                400
              ]),
          /* [] */0
        ]
      ]
    ]);

var cardActions = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(/* flexEnd */924268066),
        /* :: */[
          Css.padding(Css.rem(0.8)),
          /* [] */0
        ]
      ]
    ]);

var cardAction = Css.style(/* :: */[
      Css.unsafe("flex", "0 0 auto"),
      /* :: */[
        Css.color(Css.hex(Theme$ReactHooksTemplate.colorButton)),
        /* :: */[
          Css.alignItems(/* center */98248149),
          /* :: */[
            Css.height(Css.px(48)),
            /* :: */[
              Css.justifyContent(/* center */98248149),
              /* :: */[
                Css.backgroundColor(/* transparent */582626130),
                /* :: */[
                  Css.padding(Css.rem(1.2)),
                  /* :: */[
                    Css.fontSize(Css.rem(2.4)),
                    /* :: */[
                      Css.overflow(/* visible */589592690),
                      /* :: */[
                        Css.textAlign(/* center */98248149),
                        /* :: */[
                          Css.unsafe("transition", "background-color 150ms cubic-bezier(0.4, 0, 0.2, 1) 0ms"),
                          /* :: */[
                            Css.unsafe("border", "none"),
                            /* :: */[
                              Css.borderRadius(Css.pct(50)),
                              /* :: */[
                                Css.margin(/* zero */-789508312),
                                /* :: */[
                                  Css.cursor(/* pointer */-786317123),
                                  /* :: */[
                                    Css.hover(/* :: */[
                                          Css.unsafe("background-color", "rgba(0, 0, 0, 0.08)"),
                                          /* [] */0
                                        ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* card */card,
  /* cardImageWrapper */cardImageWrapper,
  /* cardImage */cardImage,
  /* cardTitle */cardTitle,
  /* cardContent */cardContent,
  /* cardDescription */cardDescription,
  /* cardActions */cardActions,
  /* cardAction */cardAction
];

function Recipe(Props) {
  var recipe = Props.recipe;
  var match = recipe.images;
  var tmp;
  if (match !== undefined) {
    var image = Caml_array.caml_array_get(match, 0);
    var url = image.url;
    tmp = React.createElement("div", {
          className: cardImage,
          style: {
            backgroundImage: "url(\"" + (String(url) + "\")")
          }
        });
  } else {
    tmp = null;
  }
  return React.createElement("li", {
              className: card
            }, React.createElement("div", {
                  className: cardImageWrapper
                }, tmp, React.createElement("div", {
                      className: cardTitle
                    }, recipe.title)), React.createElement("div", {
                  className: cardContent
                }, React.createElement("p", {
                      className: cardDescription
                    }, recipe.description)), React.createElement("div", {
                  className: cardActions
                }, React.createElement("button", {
                      className: cardAction
                    }, React.createElement((function (prim) {
                            return ReactFeather.Edit(prim);
                          }), FeaterIcons$ReactHooksTemplate.Edit[/* makeProps */0](undefined, "#" + Theme$ReactHooksTemplate.colorButton, /* () */0)))));
}

var make = Recipe;

exports.Styles = Styles;
exports.make = make;
/* card Not a pure module */
