// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReactRouter = require("reason-react/lib/js/src/ReasonReactRouter.js");

var Styles = /* module */[];

function RecipeEdit(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var id = match[0];
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  if (id === "") {
    var match$1 = url[/* path */0];
    if (match$1) {
      if (match$1[0] === "recipe") {
        var match$2 = match$1[1];
        if (match$2) {
          var match$3 = match$2[1];
          if (match$3) {
            var id$1 = match$2[0];
            if (match$3[0] === "edit") {
              if (!match$3[1]) {
                Curry._1(match[1], (function (param) {
                        return id$1;
                      }));
              }
              
            }
            
          }
          
        }
        
      }
      
    }
    
  }
  return React.createElement("div", undefined, id);
}

var make = RecipeEdit;

exports.Styles = Styles;
exports.make = make;
/* react Not a pure module */
