// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/lib/js/src/Css.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonApollo = require("reason-apollo/lib/js/src/ReasonApollo.bs.js");
var Recipe$ReactHooksTemplate = require("./Recipe.bs.js");

var recipeList = Css.style(/* :: */[
      Css.listStyleType(/* none */-922086728),
      /* :: */[
        Css.display(/* grid */-999565626),
        /* :: */[
          Css.gridTemplateColumns(/* :: */[
                /* `repeat */[
                  108828507,
                  /* tuple */[
                    /* autoFill */652328338,
                    /* `minmax */[
                      -754859950,
                      /* tuple */[
                        Css.rem(35),
                        Css.fr(1)
                      ]
                    ]
                  ]
                ],
                /* [] */0
              ]),
          /* :: */[
            Css.gridGap(Css.rem(2.5)),
            /* :: */[
              Css.gridAutoRows(Css.rem(35)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* recipeList */recipeList];

var ppx_printed_query = "query getRecipes  {\nrecipes  {\nid  \ntitle  \ndescription  \nupdatedAt  \ncreatedAt  \nimages  {\nid  \nurl  \n}\n\n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_dict.get(Caml_option.valFromOption(match), "recipes");
    var tmp;
    if (match$1 !== undefined) {
      var value$1 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeArray(value$1);
      tmp = match$2 !== undefined ? match$2.map((function (value) {
                var match = Js_json.decodeNull(value);
                if (match !== undefined) {
                  return undefined;
                } else {
                  var match$1 = Js_json.decodeObject(value);
                  var tmp;
                  if (match$1 !== undefined) {
                    var value$1 = Caml_option.valFromOption(match$1);
                    var match$2 = Js_dict.get(value$1, "id");
                    var tmp$1;
                    if (match$2 !== undefined) {
                      var value$2 = Caml_option.valFromOption(match$2);
                      var match$3 = Js_json.decodeString(value$2);
                      tmp$1 = match$3 !== undefined ? match$3 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$2));
                    } else {
                      tmp$1 = Js_exn.raiseError("graphql_ppx: Field id on type Recipe is missing");
                    }
                    var match$4 = Js_dict.get(value$1, "title");
                    var tmp$2;
                    if (match$4 !== undefined) {
                      var value$3 = Caml_option.valFromOption(match$4);
                      var match$5 = Js_json.decodeString(value$3);
                      tmp$2 = match$5 !== undefined ? match$5 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
                    } else {
                      tmp$2 = Js_exn.raiseError("graphql_ppx: Field title on type Recipe is missing");
                    }
                    var match$6 = Js_dict.get(value$1, "description");
                    var tmp$3;
                    if (match$6 !== undefined) {
                      var value$4 = Caml_option.valFromOption(match$6);
                      var match$7 = Js_json.decodeString(value$4);
                      tmp$3 = match$7 !== undefined ? match$7 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$4));
                    } else {
                      tmp$3 = Js_exn.raiseError("graphql_ppx: Field description on type Recipe is missing");
                    }
                    var match$8 = Js_dict.get(value$1, "updatedAt");
                    var match$9 = Js_dict.get(value$1, "createdAt");
                    var match$10 = Js_dict.get(value$1, "images");
                    var tmp$4;
                    if (match$10 !== undefined) {
                      var value$5 = Caml_option.valFromOption(match$10);
                      var match$11 = Js_json.decodeNull(value$5);
                      if (match$11 !== undefined) {
                        tmp$4 = undefined;
                      } else {
                        var match$12 = Js_json.decodeArray(value$5);
                        tmp$4 = match$12 !== undefined ? match$12.map((function (value) {
                                  var match = Js_json.decodeObject(value);
                                  if (match !== undefined) {
                                    var value$1 = Caml_option.valFromOption(match);
                                    var match$1 = Js_dict.get(value$1, "id");
                                    var tmp;
                                    if (match$1 !== undefined) {
                                      var value$2 = Caml_option.valFromOption(match$1);
                                      var match$2 = Js_json.decodeString(value$2);
                                      tmp = match$2 !== undefined ? match$2 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$2));
                                    } else {
                                      tmp = Js_exn.raiseError("graphql_ppx: Field id on type Asset is missing");
                                    }
                                    var match$3 = Js_dict.get(value$1, "url");
                                    var tmp$1;
                                    if (match$3 !== undefined) {
                                      var value$3 = Caml_option.valFromOption(match$3);
                                      var match$4 = Js_json.decodeString(value$3);
                                      tmp$1 = match$4 !== undefined ? match$4 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
                                    } else {
                                      tmp$1 = Js_exn.raiseError("graphql_ppx: Field url on type Asset is missing");
                                    }
                                    return {
                                            id: tmp,
                                            url: tmp$1
                                          };
                                  } else {
                                    return Js_exn.raiseError("graphql_ppx: Object is not a value");
                                  }
                                })) : Js_exn.raiseError("graphql_ppx: Expected array, got " + JSON.stringify(value$5));
                      }
                    } else {
                      tmp$4 = undefined;
                    }
                    tmp = {
                      id: tmp$1,
                      title: tmp$2,
                      description: tmp$3,
                      updatedAt: match$8 !== undefined ? Caml_option.valFromOption(match$8) : Js_exn.raiseError("graphql_ppx: Field updatedAt on type Recipe is missing"),
                      createdAt: match$9 !== undefined ? Caml_option.valFromOption(match$9) : Js_exn.raiseError("graphql_ppx: Field createdAt on type Recipe is missing"),
                      images: tmp$4
                    };
                  } else {
                    tmp = Js_exn.raiseError("graphql_ppx: Object is not a value");
                  }
                  return Caml_option.some(tmp);
                }
              })) : Js_exn.raiseError("graphql_ppx: Expected array, got " + JSON.stringify(value$1));
    } else {
      tmp = Js_exn.raiseError("graphql_ppx: Field recipes on type Query is missing");
    }
    return {
            recipes: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function ret_type(f) {
  return /* module */[];
}

var MT_Ret = /* module */[];

var GetRecipes = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var GetRecipesQuery = ReasonApollo.CreateQuery([
      ppx_printed_query,
      parse
    ]);

function Recipes(Props) {
  var recipesQuery = make(/* () */0);
  return React.createElement("ul", {
              className: recipeList
            }, React.createElement(GetRecipesQuery[/* make */4], {
                  variables: recipesQuery.variables,
                  children: (function (param) {
                      var result = param[/* result */0];
                      if (typeof result === "number") {
                        return React.createElement("div", undefined, "Loading");
                      } else if (result.tag) {
                        var recipes = Belt_Array.keepMap(result[0].recipes, (function (recipe) {
                                return recipe;
                              }));
                        return $$Array.map((function (recipe) {
                                      return React.createElement(Recipe$ReactHooksTemplate.make, {
                                                  recipe: recipe,
                                                  key: recipe.id
                                                });
                                    }), recipes);
                      } else {
                        return React.createElement("div", undefined, result[0].message);
                      }
                    })
                }));
}

var make$1 = Recipes;

exports.Styles = Styles;
exports.GetRecipes = GetRecipes;
exports.GetRecipesQuery = GetRecipesQuery;
exports.make = make$1;
/* recipeList Not a pure module */
