// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var navHeight = 5;

var colorBg = "eeeeee";

var colorHighlight = "00adb5";

var colorBlack = "393e46";

var colorText = "222831";

exports.navHeight = navHeight;
exports.colorBg = colorBg;
exports.colorHighlight = colorHighlight;
exports.colorBlack = colorBlack;
exports.colorText = colorText;
/* No side effect */
