// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var navHeight = 5;

var colorBg = "eeeeee";

var colorHighlight = "00adb5";

var colorCyan = "11999e";

var colorBlack = "222831";

var colorText = "393e46";

var colorPink = "ff2e63";

var colorGray = "40514e";

exports.navHeight = navHeight;
exports.colorBg = colorBg;
exports.colorHighlight = colorHighlight;
exports.colorCyan = colorCyan;
exports.colorBlack = colorBlack;
exports.colorText = colorText;
exports.colorPink = colorPink;
exports.colorGray = colorGray;
/* No side effect */
